exclude: '^(examples|external|build|.vscode|acaverilog\/verilog_templates)/.*'
default_language_version:
    python: python3.9
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
        exclude: '^.vscode/.*'
    -   id: check-ast
    -   id: check-merge-conflict
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.32.0'
    hooks:
    -   id: yapf
        additional_dependencies: [toml]
        args: [--style=.style.yapf, --parallel, --in-place]
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
    -   id: clang-format
